image:
  repository: gcr.io/hyperlane-labs-dev/hyperlane-monorepo
  tag:
hyperlane:
  runEnv: mainnet3
  context: hyperlane
  chains: []
nameOverride: ''
fullnameOverride: ''
externalSecrets:
  clusterSecretStore:
